[tool.poetry]
name = "bushan-1stproject-1"
version = "0.1.0"
description = ""
authors = ["Bushan Bengaluru"]
license = "GNU"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.13.1"
datetime = "^5.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
